import { Internship } from '@/types/student';

export const SAMPLE_INTERNSHIPS: Internship[] = [
  {
    id: 'int-001',
    title: 'Frontend Intern',
    organization: 'GovTech Labs',
    sector: 'IT & Software',
    locations: ['Delhi','Remote'],
    modality: 'hybrid',
    description: 'Work on citizen-facing web apps using React and Tailwind.',
    requiredSkills: ['React','JavaScript','HTML','CSS'],
    preferredSkills: ['TypeScript','Tailwind CSS','Accessibility'],
    capacity: 10,
    stipendMin: 10000,
    stipendMax: 15000,
    durationWeeks: 12,
    applicationDeadline: '2025-10-31T23:59:59.000Z',
  },
  {
    id: 'int-002',
    title: 'Data Science Intern',
    organization: 'National Data Office',
    sector: 'Data & AI',
    locations: ['Bengaluru','Remote'],
    modality: 'remote',
    description: 'Analyze public datasets and build ML prototypes for policy insights.',
    requiredSkills: ['Python','Pandas','NumPy'],
    preferredSkills: ['Scikit-learn','Machine Learning','Data Visualization'],
    capacity: 8,
    stipendMin: 12000,
    stipendMax: 18000,
    durationWeeks: 16,
    applicationDeadline: '2025-11-15T23:59:59.000Z',
  },
  {
    id: 'int-003',
    title: 'Backend Intern',
    organization: 'Digital Services India',
    sector: 'IT & Software',
    locations: ['Hyderabad'],
    modality: 'onsite',
    description: 'Build secure APIs and services for large-scale platforms.',
    requiredSkills: ['Node.js','Express','SQL'],
    preferredSkills: ['Docker','AWS','TypeScript'],
    capacity: 6,
    stipendMin: 13000,
    stipendMax: 20000,
    durationWeeks: 20,
    applicationDeadline: '2025-11-30T23:59:59.000Z',
  },
  {
    id: 'int-004',
    title: 'AI Research Intern',
    organization: 'AI4Gov Initiative',
    sector: 'Data & AI',
    locations: ['Pune','Remote'],
    modality: 'hybrid',
    description: 'Explore NLP for citizen services; prototype models and evaluate fairness.',
    requiredSkills: ['Python','Machine Learning','NLP'],
    preferredSkills: ['PyTorch','TensorFlow','Data Ethics'],
    capacity: 4,
    stipendMin: 15000,
    stipendMax: 25000,
    durationWeeks: 10,
    applicationDeadline: '2025-10-20T23:59:59.000Z',
  }
];
